title: 'The Work Within Queue'
description: 'A Webfolio of Projects and Programs'
lsi: false
safe: true
source: /.src
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge